export const whatsappField = [
  {
    type: "input",
    inputType: "text",
    fieldName: "baseURL",
    label: "URL",
    required: true,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter1H",
    label: "UserId",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter1V",
    label: "Value",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter2H",
    label: "Password",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter2V",
    label: "Value",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter3H",
    label: "Addt'l Parameter1",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter3V",
    label: "Value",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter4H",
    label: "Addt'l Parameter2",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "parameter4V",
    label: "Value",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "mobileH",
    label: "Mobile(p)",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "messageH",
    label: "Message(P)",
    required: false,
  },
  {
    type: "textarea",
    fieldName: "wAppBody",
    label: "Body",
    required: false,
  },
];

export const emailField = [
  {
    type: "input",
    inputType: "text",
    fieldName: "senderID",
    label: "Email Address",
    required: true,
  },
 
  {
    type: "input",
    inputType: "text",
    fieldName: "pwd",
    label: "Password",
    required: false,
  },
  {
    type: "input",
    inputType: "text",
    fieldName: "smtpServer",
    label: "Email Host",
    required: false,
  },
  {
    type: "input",
    inputType: "number",
    fieldName: "smtpPort",
    label: "Email Port",
    required: false,
  },
  {
    type: "textarea",
    fieldName: "eMailB",
    label: "Email Footer",
    required: false,
  },
  {
    type: "checkbox",
    fieldName: "emailSSL",
    label: "SSL",
    required: false,
  },
];
export const busyField = [
  {
    type: "checkbox",
    fieldName: "busyIntegration",
    label: "Busy Integration",
    required: false,
  },
  {
    type: "checkbox",
    fieldName: "locationIntegration",
    label: "Location Enable",
    required: false,
  },
  {
    type: "select",
    fieldName: "oF",
    label: "Assets Item OF",
    required: false,
    options: [
        { label: "OF1", value: 1 },
        { label: "OF2", value: 2 },
        { label: "OF3", value: 3 },
        { label: "OF4", value: 4 },
        { label: "OF5", value: 5 },
        { label: "OF6", value: 6 },
        { label: "OF7", value: 7 },
        { label: "OF8", value: 8 },
        { label: "OF9", value: 9 },
        { label: "OF10", value: 10 },
    ],
  },
];
